### ISSUE TITLE
无法编译处jar

### ISSUE THREAD

**Issue by zhzhdoai** [Adrninistrator/java-all-call-graph#1]
师傅，这项目编译不了处可运行jar : https://github.com/Adrninistrator/java-callgraph

**Comment by Adrninistrator** [comment]
gradlew jar
是可以编译的哈

**Comment by zhzhdoai** [comment]
java -jar java-callgraph-master-2-0.0.2.jar 
java-callgraph-master-2-0.0.2.jar中没有主清单属性

**Comment by Adrninistrator** [comment]
依赖的jar包比较多，最好在IDE中使用，不然需要把依赖的jar包也指定到classpath中

如果只需要编译好的jar包的话，可以从下面的地址下载
https://repo1.maven.org/maven2/com/github/adrninistrator/java-all-call-graph/0.0.4/java-all-call-graph-0.0.4.jar
