### ISSUE TITLE
向下调用链能否支持整个类的分析

### ISSUE THREAD

**Issue by beanww** [Adrninistrator/java-all-call-graph#10]
目前发现
o_g4caller_entry_method.properties
必须指定类名和方法信息，比如 XXAction:func1

能否不写方法信息分析整个类的向下调用链？即:配置为 XXAction:

谢谢！

**Comment by Adrninistrator** [comment]
之前考虑某个类所有方法向下找的需求可能会比较少，一个类对外提供的方法一般也比较少，所以没有实现，这样的场景多吗

**Comment by beanww** [comment]
因为要梳理业务，从Controller层入手分析所有涉及的Mapper

结合您的框架来看，这个场景似乎应该生成多个调用链日志文件才合理，即发现向下分析涉及多个方法时，则独立完成多个方法的分析日志输出

**Comment by Adrninistrator** [comment]
好的，这几天我加一下支持在配置文件只指定类名的使用方式

**Comment by Adrninistrator** [comment]
这个功能加上了哈，可以试用一下最新版

**Comment by beanww** [comment]
已验证可用，多谢！
