### ISSUE TITLE
支持多模块项目的类图生成么

### ISSUE THREAD

**Issue by dnlixiaoxin** [Adrninistrator/java-all-call-graph#3]
期待回复～

**Comment by Adrninistrator** [comment]
这是来自zhengyi的邮箱的自动回复邮件。您好，您给我发邮件时我的邮箱未打开，我无法亲自回复您的邮件。我将在进入邮箱后，尽快给您回复。

**Comment by Adrninistrator** [comment]
多模块是指多个java工程，或者一个java工程里分了几个目录的情况吗，如果是像上面这样的话，这些都是支持的，只要把相关的目录分别编译成对应的jar包，在配置文件里把相关的jar包路径都配置进去就可以了

如果是需要支持保存了编译好的class文件的目录，现在还不支持，正在实现这个功能，过一段时间会更新进来

**Comment by dnlixiaoxin** [comment]
是一个java项目有多个目录，看上去都是支持的，那应该就可以使用了
