### ISSUE TITLE
求教，引入依赖后，无法拿到UnzipFile类是怎么回事

### ISSUE THREAD

**Issue by KyleWong2007** [Adrninistrator/java-all-call-graph#49]
![image](https://github.com/Adrninistrator/java-all-call-graph/assets/100743754/6a60efbb-efe6-40d6-86a6-d23b45b81cbe)
![image](https://github.com/Adrninistrator/java-all-call-graph/assets/100743754/a3f45b36-5e80-434b-86d0-e98fa7426bfe)

**Comment by Adrninistrator** [comment]
刷新一下Maven依赖，看一下IDEA的项目依赖的jar包列表里有没有这个jar包，如果有的话可以打开这个jar包直接执行UnzipFile类
或者是尝试在不同的模块（main/test）里创建上面的测试类看能不能找到
