### ISSUE TITLE
无法找到  org.springframework.web.bind.annotation.RestController 类型的controller

### ISSUE THREAD

**Issue by javazhangyi** [Adrninistrator/java-all-call-graph#58]
一下类型的spring controller 无法扫描到

@RestController
public class TestController {
	@PostMapping("/atp/agent/startup/instance/method/link")
	public Object link(@RequestBody Object object){
		return object;
	}
}

因为com.adrninistrator.jacg.common.JACGCommonNameConstants 类 不包含  RestController类型

    public static final String[] SPRING_MVC_MAPPING_ANNOTATIONS = new String[]{
            "org.springframework.web.bind.annotation.RequestMapping",
            "org.springframework.web.bind.annotation.DeleteMapping",
            "org.springframework.web.bind.annotation.GetMapping",
            "org.springframework.web.bind.annotation.PatchMapping",
            "org.springframework.web.bind.annotation.PostMapping",
            "org.springframework.web.bind.annotation.PutMapping"
    };

**Comment by Adrninistrator** [comment]
好的，这里我改一下
