### ISSUE TITLE
new RunnerWriteDb().run() 异常

### ISSUE THREAD

**Issue by javazhangyi** [Adrninistrator/java-all-call-graph#59]
分析开源项目 pig-upms（https://github.com/pig-mesh/pig） 报错

报错位置：
org.apache.bcel.classfile.ClassFormatException: Invalid method signature: Ljava/lang/String;
	at org.apache.bcel.generic.Type.getArgumentTypes(Type.java:89)
	at com.adrninistrator.javacg.util.JavaCGBootstrapMethodUtil.getMethodFromConstantMethodHandle(JavaCGBootstrapMethodUtil.java:96)
	at com.adrninistrator.javacg.util.JavaCGBootstrapMethodUtil.getBootstrapMethodInfo(JavaCGBootstrapMethodUtil.java:58)

源代码

![Uploading image.png…]()

jar_dir.properties 参数
pig-upms/pig-upms-biz/target/pig-upms-biz.jar
tmp-9d7780996ff09167/BOOT-INF/lib/pig-common-oss-3.7.5.jar
tmp-9d7780996ff09167/BOOT-INF/lib/pig-common-log-3.7.5.jar
tmp-9d7780996ff09167/BOOT-INF/lib/pig-common-core-3.7.5.jar
tmp-9d7780996ff09167/BOOT-INF/lib/pig-common-security-3.7.5.jar
tmp-9d7780996ff09167/BOOT-INF/lib/pig-common-xss-3.7.5.jar
tmp-9d7780996ff09167/BOOT-INF/lib/pig-common-mybatis-3.7.5.jar
tmp-9d7780996ff09167/BOOT-INF/lib/pig-upms-api-3.7.5.jar
tmp-9d7780996ff09167/BOOT-INF/lib/pig-common-feign-3.7.5.jar
tmp-9d7780996ff09167/BOOT-INF/lib/pig-common-swagger-3.7.5.jar

**Comment by javazhangyi** [comment]
Master

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年03月19日 22:22 |
| 收件人 | Adrninistrator/java-all-call-graph ***@***.***> |
| 抄送人 | zhangyi ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [Adrninistrator/java-all-call-graph] new RunnerWriteDb().run() 异常 (Issue #59) |

是通过哪个分支编译的，我试一下

**Comment by Adrninistrator** [comment]
应该是用JDK17分支编译的，我再试一下

**Comment by Adrninistrator** [comment]
com.github.adrninistrator
java-callgraph2
1.0.17

请使用这个版本，解决了上面的问题

**Comment by javazhangyi** [comment]
感谢
