### ISSUE TITLE
想搞一个无数据库的版本

### ISSUE THREAD

**Issue by RespectandLove** [Adrninistrator/java-all-call-graph#60]

**Comment by Adrninistrator** [comment]
无数据库的版本是指分析过程不用数据库吗

**Comment by RespectandLove** [comment]
是的,现在过程分析全部基于数据库。我觉得可以基于内存分析。目前我有这方面的计划

**Comment by Adrninistrator** [comment]
现在支持MySQL或者H2数据库，H2数据库是一个单独的文件，不依赖数据库服务器，看这种方式能不能满足你的要求
用SQL处理数据比自己处理还是方便一些

**Comment by RespectandLove** [comment]
我的想法是作为maven的插件化,所以想极大程度减少内存的使用
