### ISSUE TITLE
RunnerGenAllGraph4Callee#doCombineClassFile结果合并会清空原文件

### ISSUE THREAD

**Issue by zhzhdoai** [Adrninistrator/java-all-call-graph#64]
最后会调用JavaCGFileUtil.class#genBufferedWriter
    public static BufferedWriter genBufferedWriter(String filePath) throws FileNotFoundException {
        return new BufferedWriter(new OutputStreamWriter(new FileOutputStream(filePath), StandardCharsets.UTF_8));
    }

应该写成
new BufferedWriter(new OutputStreamWriter(new FileOutputStream(filePath, true), StandardCharsets.UTF_8));

**Comment by Adrninistrator** [comment]
最新的版本没有做合并的处理了，还同提交，我改一下这个方法，支持指定是否覆盖
