### ISSUE TITLE
child1impl类继承abstract1类，实现interface1，ToDoClass调用接口某方法调用缺失

### ISSUE THREAD

**Issue by zhzhdoai** [Adrninistrator/java-all-call-graph#65]
public class TodoClass extends abstractHandler {
	
		public void func(map){
			InterfaceHandler hander = HandlerFactory.getHandler("xxx");
			handler.undo(map);

		}

}

public abstract AbstractHandler implements InterfaceHandler{
	
}

public interface interfaceHandler {
	Map undo(Map var1);
}

public class childHander  extends AbstractHandler{
	public Map undo(Map var1){
		return map;
	}
}

callee模式调用，展示调用关系缺失
仅展示AbstractHandler:unpack -> childHander:unpack, 未能够进一步连接到TodoClass:undo方法调用。
但是method_call_info存在TodoClass:undo -> interfaceHandler:undo调用关系

**Comment by zhzhdoai** [comment]
正确调用应该是TodoClass:undo -> interfaceHandler:undo -> childHander:undo . 最后结果却是 AbstractHandler:unpack -> childHander:unpack

**Comment by zhzhdoai** [comment]
没事了师傅，我二开出问题了哈哈哈

**Comment by Adrninistrator** [comment]
这是来自zhengyi的邮箱的自动回复邮件。您好，您给我发邮件时我的邮箱未打开，我无法亲自回复您的邮件。我将在进入邮箱后，尽快给您回复。
