### ISSUE TITLE
android项目使用

### ISSUE THREAD

**Issue by zys942138046** [Adrninistrator/java-all-call-graph#70]
我用的android项目发现使用ide方式不行，因为unzipJACG使用了getProtectionDomain接口android不支持。
然后我换了命令方式，发现会有 错误: 程序包javax.annotation不存在。
这个需要build.gradle里面补充implementation 'javax.annotation:javax.annotation-api:1.3.2'。
就可以生成jar包了。

**Comment by Adrninistrator** [comment]
这是来自zhengyi的邮箱的自动回复邮件。您好，您给我发邮件时我的邮箱未打开，我无法亲自回复您的邮件。我将在进入邮箱后，尽快给您回复。

**Comment by Adrninistrator** [comment]
是在比较高的JDK版本运行的吗，高版本javax依赖是需要单独添加一下
