### ISSUE TITLE
请问原理是否是字节码静态分析？

### ISSUE THREAD

**Issue by NasdaqGodzilla** [Adrninistrator/java-all-call-graph#9]

**Comment by Adrninistrator** [comment]
是的哈，在这个项目里
[https://github.com/Adrninistrator/java-callgraph2](https://github.com/Adrninistrator/java-callgraph2)
使用的BCEL

**Comment by NasdaqGodzilla** [comment]
那是否可以支持：
1. 提供release jar包，可以避免使用前 gradlew编译
2. 不需集成进入源工程中，通过启动参数对指定的class文件或jar包进行静态分析即可。

**Comment by Adrninistrator** [comment]
支持
1.参考 [https://github.com/Adrninistrator/java-all-call-graph/blob/main/how_to_use.md#133-%E7%94%9F%E6%88%90java%E6%96%B9%E6%B3%95%E8%B0%83%E7%94%A8%E5%85%B3%E7%B3%BB%E5%B9%B6%E5%86%99%E5%85%A5%E6%95%B0%E6%8D%AE%E5%BA%93](https://github.com/Adrninistrator/java-all-call-graph/blob/main/how_to_use.md#133-%E7%94%9F%E6%88%90java%E6%96%B9%E6%B3%95%E8%B0%83%E7%94%A8%E5%85%B3%E7%B3%BB%E5%B9%B6%E5%86%99%E5%85%A5%E6%95%B0%E6%8D%AE%E5%BA%93)，通过~jacg_config/config.properties配置文件的参数：call.graph.jar.list可以指定jar包或者class文件所在目录
2.如果不希望在IDE执行，需要在命令行直接执行，参考[https://github.com/Adrninistrator/java-all-call-graph/blob/main/how_to_use.md#14-%E4%BD%BF%E7%94%A8%E5%91%BD%E4%BB%A4%E8%A1%8C%E6%96%B9%E5%BC%8F%E6%89%A7%E8%A1%8C](https://github.com/Adrninistrator/java-all-call-graph/blob/main/how_to_use.md#14-%E4%BD%BF%E7%94%A8%E5%91%BD%E4%BB%A4%E8%A1%8C%E6%96%B9%E5%BC%8F%E6%89%A7%E8%A1%8C)

**Comment by NasdaqGodzilla** [comment]
感谢

**Comment by NasdaqGodzilla** [comment]
感谢
